### ISSUE TITLE
Password field should not display characters

### ISSUE THREAD

**Issue by edwardball** [EMT/see-do#57]
![image](https://cloud.githubusercontent.com/assets/3170121/12146455/9dc71cac-b48b-11e5-887f-80050b4b571e.png)

**Comment by hparton** [comment]
![post-42510-it-crowd-maurice-moss-fire-gif-6zwo](https://cloud.githubusercontent.com/assets/5281898/12146743/3a29dae8-b48d-11e5-9f62-26285d514b2d.gif)
